apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        volumeMounts:
         - name: redis-data
           mountPath: /data
        readinessProbe:
         initialDelaySeconds: 5
         periodSeconds: 5
         tcpSocket:
           port: 6379
        livenessProbe:
         initialDelaySeconds: 5
         periodSeconds: 5
         tcpSocket:
           port: 6379
        resources:
         requests:
          cpu: 100m
          memory: 100Mi
         limits:
          cpu: 120m
          memory: 200Mi
      volumes:
       - name: redis-data
         emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379